- alias: Garage door is opened!
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.garage_sensor_2_0
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: script.garage_door_alarm
- alias: Garage door was closed!
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.garage_sensor_2_0
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: script.garage_door_alarm
- alias: Power usage is low
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.power_usage_low
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.kevin
    data:
      title: "Power usage is low!"
      message: "The power usage has been below 500 watts for 30 minutes!"
- alias: Garage door battery low
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_sourcenodeid_2_2
    value_template: "{{ state.attributes.battery_level }}"
    below: 15
  action:
    service: notify.kevin
    data:
      title: "Garage sensor battery is low."
      message: "Make sure you have a CR-123A battery and consider replacing."
- alias: Family Room Lights On
  trigger:
    platform: state
    entity_id: switch.ge_12722_onoff_relay_switch_switch_8_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.ge_12721_lighting_control_duplex_receptacle_switch_7_0
- alias: Family Room Lights Off
  trigger:
    platform: state
    entity_id: switch.ge_12722_onoff_relay_switch_switch_8_0
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.ge_12721_lighting_control_duplex_receptacle_switch_7_0
- alias: Light When Garage Is Opened
  trigger:
    platform: state
    entity_id: binary_sensor.garage_sensor_2_0
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: light.ge_12724_3way_dimmer_switch_level_9_0
      data:
        brightness: 128
    - service: homeassistant.turn_on
      entity_id: script.garage_door_light
- alias: Garage Door Light Turned Off
  trigger:
    platform: state
    entity_id: light.ge_12724_3way_dimmer_switch_level_9_0
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: script.garage_door_light
- alias: Time for the bus
  trigger:
    platform: time
    at: '07:37:00'
  condition:
    - condition: time
      weekday:
        - tue
        - wed
        - thu
        - fri
  action:
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data:
        message: "It's time for the bus, have a wonderful day!"
- alias: Time for the bus
  trigger:
    platform: time
    at: '07:37:00'
  condition:
    - condition: time
      weekday:
        - mon
  action:
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data:
        message: "It's time for the bus, don't forget your clarinet! Have a wonderful day!"
- alias: Good Morning Jacob
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - thu
        - mon
  action:
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data:
        message: "It's not time for the bus because it's summer! Have a great day!"
- alias: Evening
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
     condition: or
     conditions:
       - condition: state
         entity_id: 'device_tracker.pi_katie'
         state: 'home'
       - condition: state
         entity_id: 'device_tracker.pi_kevin'
         state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.ge_12722_onoff_relay_switch_switch_8_0
    - service: homeassistant.turn_on
      entity_id: light.ge_12724_3way_dimmer_switch_level_9_0
    - service: homeassistant.turn_on
      entity_id: switch.ge_12722_onoff_relay_switch_switch_11_0
- alias: Sleep Time
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ge_12722_onoff_relay_switch_switch_8_0
    - service: homeassistant.turn_off
      entity_id: light.ge_12724_3way_dimmer_switch_level_9_0
    - service: homeassistant.turn_off
      entity_id: switch.ge_12722_onoff_relay_switch_switch_11_0


