homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 194
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  # Customize device settings
  customize:
    media_player.bedroom:
      friendly_name: Bedroom Chromecast
      icon: mdi:television
    binary_sensor.garage_sensor:
      polling_intensity: 1
      sensor_class: opening
    script.garage_door_alarm:
      hidden: true
    script.trigger_garage_door:
      hidden: true
    script.close_garage_door:
      hidden: true
    script.open_garage_door:
      hidden: true
    switch.linear_fs20z_isolated_contact_fixture_module_switch:
      friendly_name: Garage Door Relay
      hidden: true
      google_assistant: false
    switch.garage:
      google_assistant: false
    sensor.garage_alarm_level_2_1:
      hidden: true
    sensor.garage_alarm_type_2_0:
      hidden: true
    sensor.garage_burglar_2_10:
      hidden: true
    sensor.garage_sourcenodeid_2_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0:
      polling_intensity: 1
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8:
      polling_intensity: 1
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1_3:
      hidden: true
    switch.family_room_switch_switch:
      friendly_name: Family Room Light
    switch.family_room_outlet_switch:
      friendly_name: Family Room Outlet
      hidden: true
    switch.front_porch_outlet_switch:
      friendly_name: Front Porch Outlet
    switch.outdoor_garage_lights_switch:
      friendly_name: Outdoor Garage Lights
    light.garage_entrance_dimmer_level:
      friendly_name: Garage Door Dimmer
    light.living_room_switch_level:
      friendly_name: Living Room Light
    light.stairway_dimmer_level:
      friendly_name: Stairway Dimmer
    light.upstairs_hallway_dimmer_level:
      friendly_name: Upstairs Hallway Dimmer
    light.front_hallway_dimmer_level:
      friendly_name: Front Hallway Dimmer
    light.master_bedroom_level:
      friendly_name: Master Bedroom Dimmer

# Enable the map
map:

# Enables the frontend
frontend:
  javascript_version: latest

logger:
  default: critical
  #  logs:
  #    homeassistant.components.zwave: debug

recorder:
  db_url: mysql://homeassistant:Woovo5ko@127.0.0.1/hass

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_api_password
  ssl_certificate: /etc/letsencrypt/live/home.sivic.me/fullchain.pem
  ssl_key: /etc/letsencrypt/live/home.sivic.me/privkey.pem
  base_url: https://home.sivic.me

weblink:
  entities:
    - name: Energy Monitor
      url: http://home.sivic.me:8122/emoncms/

panel_iframe:
  energy_monitor:
    title: Energy Monitor
    url: !secret emoncms_monitor_url
    icon: mdi:chart-line

# Groups
group:
  default_view:
    name: Home
    view: yes
    entities:
      - group.people
      - group.garage
      - group.weather
      - group.lights
      - group.fans
      - group.links
      - scene.lights_on
  garage:
    name: Garage
    entities:
      - cover.garage_door
  people:
    name: People
    entities:
      - device_tracker.pi_katie
      - device_tracker.pi_kevin
      - device_tracker.pi_jacob
  energy_view: 
    name: Energy
    view: yes
    entities:
      - group.energy
  energy:
    name: Energy Sensors
    entities:
      - sensor.aeotec_dsb09104_home_energy_meter_power
      - sensor.aeotec_dsb09104_home_energy_meter_energy
      - binary_sensor.power_usage_low
  weather:
    name: Weather
    entities:
      - sun.sun
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
  media_players:
    name: Media Players
    view: yes
    entities:
      - group.speakers
      - group.speaker_groups
      - group.chromecasts
  speakers:
    name: Speakers
    entities:
      - media_player.kitchen_home
      - media_player.master_bedroom_home
      - media_player.jacobs_bedroom_speaker
      - media_player.emmas_room_speaker
  speaker_groups:
    name: Speaker Groups
    entities:
      - media_player.upstairs
  chromecasts:
    name: Chromecasts
    entities:
      - media_player.living_room_tv
      - media_player.bedroom_tv
  scenes:
    name: Scenes
    view: yes
    entities:
      - scene.morning
      - scene.daytime
      - scene.overcast
      - scene.evening
      - scene.bedtime
      - scene.dim_hallway
      - scene.christmas
      - scene.christmas_off
      - scene.alloff
      - scene.watching_living_room_tv
  lights:
    name: Lights
    entities:
      - switch.family_room_switch_switch
      - switch.family_room_outlet_switch
      - light.garage_entrance_dimmer_level
      - light.living_room_switch_level
      - light.stairway_dimmer_level
      - light.upstairs_hallway_dimmer_level
      - switch.front_porch_outlet_switch
      - switch.outdoor_garage_lights_switch
      - light.front_hallway_dimmer_level
      - light.master_bedroom_level
      - light.kitchen
      - light.kitchen_table
      - light.front_porch
      - light.front_door
      - light.jacobs_bedroom
      - light.madelyns_bedroom
      - light.emmas_bedroom
  fans:
    name: Fans
    entities:
      - fan.living_room
  links:
    name: Links
    entities:
      - weblink.router
      - weblink.energy_monitor
  pi_stats:
    name: Pi Stats
    view: yes
    entities:
      - group.home_assistant_stats
  home_assistant_stats:
    name: Home Assistant Server
    entities:
      - sensor.home_assistant_cpu_load
      - sensor.home_assistant_disk_free
      - sensor.home_assistant_disk_use
      - sensor.home_assistant_disk_use_2
      - sensor.home_assistant_ram_free
      - sensor.home_assistant_ram_use
      - sensor.home_assistant_ram_use_2
      - sensor.home_assistant_swap_free
      - sensor.home_assistant_swap_use
      - sensor.home_assistant_thread
      - sensor.home_assistant_total
      - sensor.home_assistant_running
      - sensor.home_assistant_sleeping
  automations:
    name: Automations
    entities:
      - automation.bedtime
      - automation.bus_on_a_band_day
      - automation.christmas
      - automation.christmas_lights_off
      - automation.evening
      - automation.family_room_lights_off
      - automation.family_room_lights_on
      - automation.garage_door_battery_low
      - automation.garage_door_is_opened
      - automation.garage_door_was_closed
      - automation.kids_bedtime
      - automation.light_when_arrive_home
      - automation.living_room_too_dim
      - automation.living_room_tv_stopped
      - automation.master_bedroom_tv_stopped
      - automation.morning
      - automation.no_ones_home
      - automation.overcast
      - automation.power_usage_is_low
      - automation.rain_stopped
      - automation.time_for_the_bus
      - automation.watching_the_living_room_tv
      - automation.watching_the_master_bedroom_tv
  automations_view:
    name: Automations
    view: yes
    entities:
      - group.automations

switch:
  - platform: template
    switches:
      garage:
        friendly_name: 'Garage'
        value_template: "{{ is_state('binary_sensor.garage_sensor', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: script.trigger_garage_door
        turn_off:
          service: homeassistant.turn_on
          entity_id: script.trigger_garage_door

# enable the mobile app integration
mobile_app:

# Enable the system health component
system_health:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Enables support for energy tracking in EmonCMS
emoncms_history:
  api_key: !secret emoncms_api_key
  url: http://192.168.86.253/emoncms
  inputnode: 1
  whitelist:
    - sensor.aeotec_dsb09104_home_energy_meter_interval
    - sensor.aeotec_dsb09104_home_energy_meter_power_4
    - sensor.aeotec_dsb09104_home_energy_meter
#    - sensor.aeotec_dsb09104_home_energy_meter_interval_6_2
#    - sensor.aeotec_dsb09104_home_energy_meter_power_6_8
#    - sensor.aeotec_dsb09104_home_energy_meter_energy_6_0

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors 
sensor:
#  - platform: yr
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - icon
      - temperature
      - apparent_temperature
      - humidity
      - precip_intensity
      - cloud_cover
  - platform: glances
    host: 127.0.0.1
    name: Home Assistant
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: 192.168.86.253
    name: EmonCMS
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'

binary_sensor:
  - platform: template
    sensors:
      power_usage_low:
        friendly_name: Power Usage Is Low!
        value_template: '{% if states.sensor.aeotec_dsb09104_home_energy_meter_power_6_8.state %}{{ states.sensor.aeotec_dsb09104_home_energy_meter_power_6_8.state | float < 500 }}{% endif %}'

# Text to speech
tts:
  platform: google_translate

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: !secret mqtt_password

config:

# Enable Z-Wave controller
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000
  #  debug: true

# Pushbullet notifications
notify:
  - name: kevin
    platform: pushbullet
    api_key: !secret kevin_pushbullet_api_key
  - name: katie
    platform: pushbullet
    api_key: !secret katie_pushbullet_api_key

# Scenes
scene: !include_dir_list scenes

# Automations
automation: !include automations.yaml

# Covers
cover: !include covers.yaml

script:
  garage_door_alarm:
    alias: "Garage Door Alarm"
    sequence:
      - delay: 
          minutes: 10
      - service: notify.kevin
        data:
          title: "Garage is open"
          message: "The garage has been open for 10 minutes!"
      - service: notify.katie
        data:
          title: "Garage is open"
          message: "The garage has been open for 10 minutes!"
  garage_door_light:
    alias: "Turn Off Garage Door Light after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        entity_id: light.garage_entrance_dimmer_level
  trigger_garage_door:
    alias: "Trigger Garage Door"
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch
  close_garage_door:
    alias: "Close Garage Door"
    sequence:
      - condition: state
        entity_id: binary_sensor.garage_sensor
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch
  open_garage_door:
    alias: "Open Garage Door"
    sequence:
      - condition: state
        entity_id: binary_sensor.garage_sensor
        state: 'off'
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch


# Presence Detection
#device_tracker:
#  - platform: owntracks
#    new_device_defaults:
#      track_new_devices: false

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 500
    icon: mdi:home-assistant
  - name: "Middle School"
    latitude: 42.989549
    longitude: -78.609802
    radius: 750
    icon: mdi:school

google_assistant:
  project_id: sivic-homeassistant
  api_key: AIzaSyCz8gWKpFtqWV_f72QBeTJtKh_N_pWvhfU
  exposed_domains:
    - switch
    - light
    - scene
  expose_by_default: true

light:
  - platform: mqtt
    schema: json
    name: cabinet_light_1
    state_topic: "home/cabinet1"
    command_topic: "home/cabinet1/set"
    brightness: true
    rgb: true
    white_value: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash]
    optimistic: false
    qos: 0

input_boolean:
  lights_off_away:
    name: Turn Lights off when away
    icon: mdi:home-account
