homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 194
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  # Customize device settings
  customize:
    media_player.bedroom:
      friendly_name: Bedroom Chromecast
      icon: mdi:television
    binary_sensor.garage_sensor_2_0:
      polling_intensity: 1
      sensor_class: opening
    script.garage_door_alarm:
      hidden: true
    script.trigger_garage_door:
      hidden: true
    script.close_garage_door:
      hidden: true
    script.open_garage_door:
      hidden: true
    switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0:
      friendly_name: Garage Door Relay
      hidden: true
    sensor.garage_alarm_level_2_1:
      hidden: true
    sensor.garage_alarm_type_2_0:
      hidden: true
    sensor.garage_burglar_2_10:
      hidden: true
    sensor.garage_sourcenodeid_2_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0:
      polling_intensity: 1
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_energy_6_0_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_exporting_6_32_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_interval_6_2_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_4_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8:
      polling_intensity: 1
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_power_6_8_3:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1_2:
      hidden: true
    sensor.aeotec_dsb09104_home_energy_meter_previous_reading_6_1_3:
      hidden: true
    switch.ge_12722_onoff_relay_switch_switch_8_0:
      friendly_name: Family Room Light
    switch.ge_12721_lighting_control_duplex_receptacle_switch_7_0:
      friendly_name: Family Room Outlet
      hidden: true
    switch.ge_12722_onoff_relay_switch_switch_10_0:
      friendly_name: Front Porch Outlet
    switch.ge_12722_onoff_relay_switch_switch_11_0:
      friendly_name: Outdoor Garage Lights
    light.ge_12724_3way_dimmer_switch_level_9_0:
      friendly_name: Garage Door Dimmer

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_api_password

weblink:
  entities:
    - name: Energy Monitor
      url: http://home.sivic.me:8122/emoncms/
    - name: Router
      url: http://192.168.29.1/

panel_iframe:
  energy_monitor:
    title: Energy Monitor
    url: !secret emoncms_monitor_url
    icon: mdi:chart-line

# Groups
group:
  default_view:
    view: yes
    entities:
      - group.people
      - group.garage
      - group.weather
      - group.lights
      - group.links
  garage:
    name: Garage
    entities:
      - binary_sensor.garage_sensor_2_0
      - script.trigger_garage_door
      - switch.garage
      - script.close_garage_door
      - script.open_garage_door
  people:
    name: People
    entities:
      - device_tracker.pi_katie
      - device_tracker.pi_kevin
  energy_monitoring: 
    name: Energy
    view: yes
    entities:
      - sensor.aeotec_dsb09104_home_energy_meter_power_6_8
      - sensor.aeotec_dsb09104_home_energy_meter_energy_6_0
      - binary_sensor.power_usage_low
  weather:
    name: Weather
    entities:
      - sun.sun
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
  media_players:
    name: Media Players
    view: yes
    entities:
      - media_player.bedroom
      - media_player.living_room
      - media_player.kitchen_home
  lights:
    name: Lights
    entities:
      - switch.ge_12722_onoff_relay_switch_switch_8_0
      - switch.ge_12721_lighting_control_duplex_receptacle_switch_7_0
      - light.ge_12724_3way_dimmer_switch_level_9_0
      - switch.ge_12722_onoff_relay_switch_switch_10_0
      - switch.ge_12722_onoff_relay_switch_switch_11_0
  links:
    name: Links
    entities:
      - weblink.router
      - weblink.energy_monitor

switch:
  - platform: template
    switches:
      garage:
        friendly_name: 'Garage'
        value_template: "{{ is_state('binary_sensor.garage_sensor_2_0', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: script.trigger_garage_door
        turn_off:
          service: homeassistant.turn_on
          entity_id: script.trigger_garage_door

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Enables support for energy tracking in EmonCMS
emoncms_history:
  api_key: !secret emoncms_api_key
  url: http://192.168.29.254/emoncms
  inputnode: 1
  whitelist:
    - sensor.aeotec_dsb09104_home_energy_meter_interval_6_2
    - sensor.aeotec_dsb09104_home_energy_meter_power_6_8
    - sensor.aeotec_dsb09104_home_energy_meter_energy_6_0

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors 
sensor:
#  - platform: yr
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - icon
      - temperature
      - apparent_temperature
      - humidity
      - precip_intensity
  - platform: glances
    host: 127.0.0.1
    name: Home Assistant
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: 192.168.29.254
    name: EmonCMS
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'

binary_sensor:
  - platform: template
    sensors:
      power_usage_low:
        friendly_name: Power Usage Is Low!
        value_template: '{% if states.sensor.aeotec_dsb09104_home_energy_meter_power_6_8.state %}{{ states.sensor.aeotec_dsb09104_home_energy_meter_power_6_8.state | float < 500 }}{% endif %}'

# Text to speech
tts:
  platform: google

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: !secret mqtt_password

# Enable Z-Wave controller
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000
  debug: true

# Pushbullet notifications
notify:
  - name: kevin
    platform: pushbullet
    api_key: !secret kevin_pushbullet_api_key
  - name: katie
    platform: pushbullet
    api_key: !secret katie_pushbullet_api_key

# Automations
automation: !include automation.yaml

script:
  garage_door_alarm:
    alias: "Garage Door Alarm"
    sequence:
      - delay: 
          minutes: 10
      - service: notify.kevin
        data:
          title: "Garage is open"
          message: "The garage has been open for 10 minutes!"
      - service: notify.katie
        data:
          title: "Garage is open"
          message: "The garage has been open for 10 minutes!"
  garage_door_light:
    alias: "Turn Off Garage Door Light after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        entity_id: light.ge_12724_3way_dimmer_switch_level_9_0
  trigger_garage_door:
    alias: "Trigger Garage Door"
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0
  close_garage_door:
    alias: "Close Garage Door"
    sequence:
      - condition: state
        entity_id: binary_sensor.garage_sensor_2_0
        state: 'on'
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0
  open_garage_door:
    alias: "Open Garage Door"
    sequence:
      - condition: state
        entity_id: binary_sensor.garage_sensor_2_0
        state: 'off'
      - service: homeassistant.turn_on
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0
      - delay: 00:00:01
      - service: homeassistant.turn_off
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_5_0


# Presence Detection
device_tracker:
  - platform: owntracks

zone:
  name: Town
  latitude: 43.009054
  longitude: -78.636137
  radius: 20000
  passive: true
