- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_sensor', 'on') }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage
      close_cover:
        service: switch.turn_off
        data:
          entity_id: switch.garage
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage
      icon_template: >-
        {% if is_state('binary_sensor.garage_sensor', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
